version: '3'

networks:
  isolation-network:
    driver: bridge

services:
  node-auth:
    build: ./Dockerfiles/node-auth
    stdin_open: true
    tty: true
#    ports:
#      - 81:81
    command:
      - /entrypoints/squad/node-auth/entrypoint.sh
      - npm run dev
    volumes:
      - ./node-auth:/squad/node-auth
    links:
      - db

  node-api-gateway:
    build: ./Dockerfiles/node-api-gateway
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    command:
      - /entrypoints/squad/node-api-gateway/entrypoint.sh
    volumes:
      - ./node-api-gateway:/squad/node-api-gateway
    links:
#      - node-front #will send CORS req
      - node-auth
      - node-lb-creditcards

  gateway:
    build: ./Dockerfiles/gateway
    stdin_open: true
    tty: true
    ports:
      - 85:85
    command:
      - /entrypoints/squad/gateway/entrypoint.sh
    volumes:
      - ./gateway:/squad/gateway
#    networks:
#      - isolation-network

  node-front:
    build: ./Dockerfiles/node-front
    stdin_open: true
    tty: true
    ports:
#      - 8085:85
      - 80:80
    volumes:
      - ./node-front:/squad/node-front
    command:
      - /entrypoints/squad/node-front/entrypoint.sh
    links:
      - gateway:gateway
      # - node-auth
      # - node-api-gateway
#    networks:
#      - isolation-network

  node-lb-creditcards:
    build: ./Dockerfiles/node-lb-creditcards
    stdin_open: true
    tty: true
    volumes:
      - ./node-credit-cards:/squad/node-lb-creditcards
    command:
      - /entrypoints/squad/node-lb-creditcards/entrypoint.sh
    links:
      - db

  laravel-dbm:
    build: ./Dockerfiles/laravel-dbm
    stdin_open: true
    tty: true
    volumes:
      - ./laravel-dbm:/var/www/laravel-dbm
    command:
      - /entrypoints/squad/laravel-dbm/entrypoint.sh
    links:
      - db

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306