version: '3'

networks:
  isolation-network:
    driver: bridge

services:

  gateway:
    build: ./Dockerfiles/gateway
    ports:
      - 85:85
    command:
      - /entrypoints/squad/gateway/entrypoint.sh
    volumes:
      - ./gateway:/squad/gateway
    links:
      - svc-basics
      - svc-creditcards

  svc-basics:
    build: ./Dockerfiles/basics
    command:
      - /entrypoints/squad/basics/entrypoint.sh
    volumes:
      - ./svc-basics:/squad/basics
    links:
      - db

  front-end:
    build: ./Dockerfiles/front-end
    ports:
      - 80:80
    volumes:
      - ./front-end:/squad/front-end
    command:
      - /entrypoints/squad/front-end/entrypoint.sh
    links:
      - gateway:gateway

  svc-creditcards:
    build: ./Dockerfiles/svc-creditCards
    volumes:
      - ./svc-creditCards:/squad/svc-creditCards
    command:
      - /entrypoints/squad/svc-creditCards/entrypoint.sh
    links:
      - db

  laravel-dbm:
    build: ./Dockerfiles/laravel-dbm
    stdin_open: true
    volumes:
      - ./laravel-dbm:/var/www/laravel-dbm
    command:
      - /entrypoints/squad/laravel-dbm/entrypoint.sh
    links:
      - db

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306