version: '3'
services:
  node-auth:
    build: ./Dockerfiles/node-auth
    stdin_open: true
    tty: true
    ports:
      - 81:81
    command:
      - /entrypoint/entrypoint.sh
    volumes:
      - ./node-auth:/node-auth
    links:
      - db
  node-front:
    build: ./Dockerfiles/node-front
#    image: node:9
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - ./node-front:/node-front
    command:
      - /entrypoint/entrypoint.sh
    links:
      - node-auth
  laravel-dbm:
    build: ./Dockerfiles/laravel-dbm
    image: php7.2-apache:dbm
    stdin_open: true
    tty: true
    volumes:
      - ~/Projects/squadguru/laravel-dbm:/var/www/laravel-dbm
    command:
      - /var/www/entrypoint/entrypoint.sh
    links:
      - db
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306